# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: postgresql
  encoding: utf8
  database: imho_development
  pool: 5
  timeout: 5000
  username: pguser
  password: qwerty123


test:
  adapter: postgresql
  encoding: utf8
  database: imho_test
  pool: 5
  timeout: 5000
  username: pguser
  password: qwerty123

production:
  url: <%= ENV['DATABASE_URL'] %>
